apiVersion: v1
kind: Secret
metadata:
  name: bao-rabbitmq-${DEPLOY_ENV}-secret
  namespace: bao-${DEPLOY_ENV}-env
type: Opaque
data:
  RABBITMQ_DEFAULT_PASS: YWRtaW4xMjM=  # admin123 base64 encoded

