apiVersion: v2
name: database
description: A Helm chart for PostgreSQL with PgPool
type: application
version: 0.1.0
appVersion: "15"

keywords:
  - database
  - postgresql
  - pgpool

maintainers:
  - name: Gauas
    email: quocbao.job106204@gmail.com
