apiVersion: v2
name: search-engine
description: A Helm chart for MeiliSearch search engine
type: application
version: 0.1.0
appVersion: "1.7.0"

maintainers:
  - name: Gauas
    email: quocbao.job106204@gmail.com

keywords:
  - search
  - meilisearch
  - search-engine
