apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bao-${DEPLOY_ENV}-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - configMapRef:
                name: bao-${DEPLOY_ENV}-config
            - secretRef:
                name: bao-${DEPLOY_ENV}-secret
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
  namespace: bao-${DEPLOY_ENV}-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: pgpool
          image: bitnami/pgpool:4.6.2-debian-12-r4
          envFrom:
            - configMapRef:
                name: bao-${DEPLOY_ENV}-config
            - secretRef:
                name: bao-${DEPLOY_ENV}-secret
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: "0.3"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"