apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: bao-${DEPLOY_ENV}-env
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool-service
  namespace: bao-${DEPLOY_ENV}-env
spec:
  selector:
    app: pgpool
  ports:
    - name: pgpool
      port: 5432
      targetPort: 5432
  type: ClusterIP