apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dragonfly-pvc
  namespace: bao-${DEPLOY_ENV}-env
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
#  storageClassName: local-path
#
