apiVersion: v1
kind: Secret
metadata:
  name: bao-grafana-${DEPLOY_ENV}-secret
  namespace: bao-${DEPLOY_ENV}-env
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
  GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
