apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: bao-${DEPLOY_ENV}-env
spec:
  selector:
    app: rabbitmq-service
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
  type: ClusterIP
