apiVersion: v1
kind: Secret
metadata:
  name: {{ include "search-engine.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "search-engine.labels" . | nindent 4 }}
type: Opaque
data:
  MEILI_MASTER_KEY: {{ .Values.meilisearch.masterKey | b64enc | quote }}

