{{- if .Values.messageQueue.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rabbitmq-service
    {{- include "bao-application.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.messageQueue.rabbitmq.auth.username | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.messageQueue.rabbitmq.auth.password | b64enc }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.messageQueue.rabbitmq.auth.erlangCookie | b64enc }}
{{- end }}

