apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_DB: "${POSTGRES_DB}"
  PGPOOL_ADMIN_USERNAME: "${PGPOOL_ADMIN_USERNAME}"
  PGPOOL_HEALTH_CHECK_USER: "${PGPOOL_HEALTH_CHECK_USER}"
  PGPOOL_SR_CHECK_USER: "${PGPOOL_SR_CHECK_USER}"
  PGPOOL_POSTGRES_USERNAME: "${PGPOOL_POSTGRES_USERNAME}"
  PGPOOL_BACKEND_NODES: "${PGPOOL_BACKEND_NODES}"
  DEPLOY_ENV: "${DEPLOY_ENV}"