apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
  namespace: bao-${DEPLOY_ENV}-env
spec:
  selector:
    app: meilisearch-service
  ports:
    - name: http
      port: 7700
      targetPort: 7700
  type: ClusterIP

